[workspace]
resolver = "2"
members = [
    "masp_note_encryption",
    "masp_proofs",
    "masp_primitives"
]


[workspace.package]
version = "1.3.0"

[profile.release]
lto = true
panic = 'abort'
codegen-units = 1
